import { StyleSheet } from 'react-native';

export const colors = {
  background: '#f4f7fb',
  card: '#ffffff',
  border: '#d9e2ec',
  text: '#102033',
  muted: '#607083',
  primary: '#2563eb',
  primarySoft: '#dbeafe',
  success: '#16a34a',
  warning: '#b45309',
  danger: '#dc2626',
};

export const commonStyles = StyleSheet.create({
  fullScreen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screen: {
    flexGrow: 1,
    gap: 18,
    justifyContent: 'center',
    padding: 20,
  },
  title: {
    color: colors.text,
    fontSize: 30,
    fontWeight: '700',
  },
  subtitle: {
    color: colors.muted,
    fontSize: 16,
    lineHeight: 22,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  card: {
    backgroundColor: colors.card,
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 12,
    padding: 16,
  },
  selectedCard: {
    borderColor: colors.primary,
    backgroundColor: '#f8fbff',
  },
  label: {
    color: colors.text,
    fontSize: 14,
    fontWeight: '700',
  },
  input: {
    backgroundColor: '#fff',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    color: colors.text,
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 16,
  },
  sendButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  secondaryButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  pressed: {
    opacity: 0.65,
  },
  segmented: {
    backgroundColor: '#e8eef6',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 4,
    padding: 4,
  },
  segment: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    paddingVertical: 10,
  },
  segmentActive: {
    backgroundColor: '#fff',
  },
  segmentText: {
    color: colors.muted,
    fontWeight: '700',
  },
  segmentTextActive: {
    color: colors.primary,
  },
  toolbar: {
    alignItems: 'center',
    backgroundColor: '#fff',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  toolbarTitle: {
    color: colors.text,
    fontSize: 16,
    fontWeight: '700',
  },
  toolbarMeta: {
    color: colors.muted,
    fontSize: 12,
  },
  muted: {
    color: colors.muted,
    fontSize: 13,
  },
  listContent: {
    gap: 12,
    padding: 16,
  },
  sourceListContent: {
    gap: 12,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 112,
  },
  itemTitle: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '700',
  },
  emptyBox: {
    alignItems: 'center',
    gap: 8,
    padding: 28,
  },
  emptyTitle: {
    color: colors.text,
    fontSize: 18,
    fontWeight: '700',
  },
  avatar: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 8,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  avatarText: {
    color: colors.primary,
    fontSize: 20,
    fontWeight: '800',
  },
  segmentedTabs: {
    backgroundColor: '#fff',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    padding: 10,
  },
  tab: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    paddingVertical: 10,
  },
  tabActive: {
    backgroundColor: colors.primarySoft,
  },
  tabText: {
    color: colors.muted,
    fontWeight: '700',
  },
  tabTextActive: {
    color: colors.primary,
  },
  summaryBar: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  checkCircle: {
    alignItems: 'center',
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: 1,
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  checkCircleActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkText: {
    color: '#fff',
    fontWeight: '800',
  },
  chatContent: {
    gap: 12,
    padding: 16,
  },
  bubble: {
    borderRadius: 14,
    gap: 8,
    maxWidth: '88%',
    padding: 12,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: colors.primary,
  },
  assistantBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#fff',
    borderColor: colors.border,
    borderWidth: StyleSheet.hairlineWidth,
    width: '88%',
  },
  loadingBubble: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 10,
    width: 'auto',
  },
  assistantMessageContent: {
    alignSelf: 'stretch',
    gap: 8,
    minWidth: 0,
    width: '100%',
  },
  markdownContent: {
    alignSelf: 'stretch',
    minWidth: 0,
    width: '100%',
  },
  bubbleText: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 21,
  },
  userBubbleText: {
    color: '#ffffff',
    fontSize: 15,
    lineHeight: 21,
  },
  citationText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '700',
    lineHeight: 19,
  },
  citationButton: {
    alignSelf: 'flex-start',
  },
  citationRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    width: '100%',
  },
  progressText: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 17,
  },
  composerHint: {
    backgroundColor: '#fff',
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    color: colors.muted,
    fontSize: 13,
    paddingHorizontal: 12,
    paddingTop: 8,
  },
  composer: {
    alignItems: 'flex-end',
    backgroundColor: '#fff',
    borderTopColor: colors.border,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 8,
    padding: 10,
    paddingBottom: 12,
  },
  fixedToolbar: {
    backgroundColor: '#fff',
    borderBottomColor: colors.border,
    borderBottomWidth: StyleSheet.hairlineWidth,
    gap: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  sourceHeader: {
    gap: 12,
    marginBottom: 4,
  },
  sourceHeaderMeta: {
    gap: 2,
  },
  toolbarActions: {
    flexDirection: 'row',
    gap: 8,
  },
  selectionPanel: {
    backgroundColor: '#f8fafc',
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 12,
  },
  selectAllRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    minHeight: 52,
  },
  selectAllCheckbox: {
    flexShrink: 0,
    marginTop: 2,
  },
  selectAllTextBlock: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  actionPanel: {
    backgroundColor: '#fff',
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 12,
  },
  sourceActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  sourceActionButton: {
    flex: 1,
    minHeight: 48,
    minWidth: 140,
  },
  buttonDisabled: {
    opacity: 0.7,
  },
  compactButton: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    minHeight: 40,
    paddingHorizontal: 12,
  },
  compactButtonText: {
    color: colors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  progressCard: {
    backgroundColor: '#f8fafc',
    borderColor: colors.border,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 4,
    padding: 12,
  },
  progressTrack: {
    backgroundColor: '#e2e8f0',
    borderRadius: 999,
    height: 8,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: colors.primary,
    height: '100%',
  },
  modalBackdrop: {
    backgroundColor: 'rgba(15, 23, 42, 0.35)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalScrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
    gap: 12,
    padding: 16,
  },
  modalActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  modalActionButton: {
    flexGrow: 1,
    minWidth: 120,
  },
  previewCard: {
    backgroundColor: '#f8fafc',
    borderColor: colors.border,
    borderRadius: 12,
    borderWidth: StyleSheet.hairlineWidth,
    gap: 10,
    padding: 16,
  },
  previewSnippet: {
    backgroundColor: '#ffffff',
    borderColor: colors.border,
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    padding: 14,
  },
  previewMeta: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  readerChunk: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginBottom: 12,
    padding: 12,
  },
  readerChunkFocused: {
    backgroundColor: '#eff6ff',
    borderColor: colors.primary,
    borderWidth: 1,
  },
  readerChunkLabel: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 8,
  },
});

export const markdownStyles = StyleSheet.create({
  body: {
    color: colors.text,
    fontSize: 15,
    lineHeight: 21,
  },
  heading1: {
    color: colors.text,
    fontSize: 22,
    fontWeight: '800',
    lineHeight: 28,
    marginBottom: 8,
  },
  heading2: {
    color: colors.text,
    fontSize: 19,
    fontWeight: '800',
    lineHeight: 25,
    marginBottom: 6,
  },
  heading3: {
    color: colors.text,
    fontSize: 17,
    fontWeight: '800',
    lineHeight: 23,
    marginBottom: 4,
  },
  paragraph: {
    marginBottom: 8,
  },
  strong: {
    fontWeight: '800',
  },
  em: {
    fontStyle: 'italic',
  },
  bullet_list: {
    marginBottom: 8,
  },
  ordered_list: {
    marginBottom: 8,
  },
  list_item: {
    marginBottom: 4,
  },
  code_inline: {
    backgroundColor: '#eef2f7',
    borderRadius: 4,
    color: '#0f172a',
    fontFamily: 'monospace',
    fontSize: 14,
    paddingHorizontal: 4,
  },
  code_block: {
    backgroundColor: '#eef2f7',
    borderRadius: 8,
    color: '#0f172a',
    fontFamily: 'monospace',
    fontSize: 13,
    lineHeight: 18,
    padding: 10,
  },
  fence: {
    backgroundColor: '#eef2f7',
    borderRadius: 8,
    color: '#0f172a',
    fontFamily: 'monospace',
    fontSize: 13,
    lineHeight: 18,
    padding: 10,
  },
  blockquote: {
    backgroundColor: '#f8fafc',
    borderLeftColor: colors.primary,
    borderLeftWidth: 3,
    color: colors.muted,
    marginBottom: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
});
